# Site wide configuration

title: VIP LAB Archive
locale: en_US
description: SNU GSDS Visual Information Processing(VIP) Lab Archive site
logo: site-logo.png
search: true
url: https://snuviplab.github.io
#url: http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: VIP-Lab
  avatar: https://avatars3.githubusercontent.com/u/283294?v=2&s=460
  email: snuviplab@gmail.com
  disqus-shortname: yskim_test
  twitter: #username
  facebook: #username
  github: snuviplab
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: # dominic.chambers@gmail.com
    analytics: # UA-55018454-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
